### ISSUE TITLE
FullJoin.io not reachable

### ISSUE THREAD

**Issue by snuzi** [sumodirjo/engineering-blogs#97]
Hi,
Does anyone know why FullJoin.io is not reachable? Is this project dead?

**Comment by sumodirjo** [comment]
@sportanova create PR for fulljoin.io in #93. I check the DNS is not resolvable. Not sure what happen to the project.

@snuzi May I know why do you open issue in this repo regarding fulljoin.io?

**Comment by snuzi** [comment]
@sumodirjo I created an issue to ask the comunity here because it is part of the list. Thanks
